### ISSUE TITLE
In IE scrollintoView borks and shows native scrollbars

### ISSUE THREAD

**Issue by abdulkareemnalband** [Grsmto/simplebar#127]
plunker here http://plnkr.co/edit/mJgyzqOVGKLaDtx5T5gV?p=preview

you can see that we can not scroll to top after this.

**Comment by Grsmto** [comment]
Hey,
I tested this in IE10 and IE11 and couldn't replicate the issue. It's probably got fixed in the new version.
Thanks!

**Comment by abdulkareemnalband** [comment]
@Grsmto can you reopen as it still happens on IE 11.0

![image](https://user-images.githubusercontent.com/3139353/38232037-f46a985a-3732-11e8-8671-f5fdfc134ae7.png)



![image](https://user-images.githubusercontent.com/3139353/38232028-e83ea8dc-3732-11e8-941e-74073ec337c6.png)

**Comment by jackdh** [comment]
Hey @abdulkareemnalband Did you get a fix for this? I'm running into the same issue.
