### ISSUE TITLE
scrollheight issue when positioned absolute element in parent relative position overflow from container!

### ISSUE THREAD

**Issue by AminRahimi** [Grsmto/simplebar#172]
hi @Grsmto 
sorry for my bad english!
when a child absolutely positioned in parent with relative position and child position case overflow from container scroll height of simplebar breaks!

scrollheight issue when positioned absolute element in parent relative position overflow from container!

https://codepen.io/aminrahimi/full/ZoZRve/

for example bootstrap dropdown has a ul absolute position and when that are in bottom of container and toggle to open ul displayed and cases simplebar  breaks

**Comment by Grsmto** [comment]
This should be fixed in latest version.

**Comment by yamelkaya** [comment]
Seems the issue is still reproduced when scrolled element initially doesn't have scrolling. Please check an example below based on the previous one. 

https://codepen.io/yamelkaya/pen/LKKWRV

**Comment by yamelkaya** [comment]
@Grsmto Did you have time to check my example which reproduces scrolling issue for absolute positioning?

**Comment by Grsmto** [comment]
@yamelkaya I did. I don't think we can do anything about that, it seems like a limitation.
The reason is that there is no way to detect the change in this scenario has there is no resize happening, the resizeObserver doesn't kick in.
That's a case where you will have to call the `resize()` function manually!

**Comment by yamelkaya** [comment]
Ok, I've got it. Thanks for the reply.
