### ISSUE TITLE
Scroll wheel and horizontal scrolling not working

### ISSUE THREAD

**Issue by JDGHHou** [Grsmto/simplebar#183]
In Chrome: scroll wheel over "data-simplebar" tagged element was, at first, properly overriding the browser scrollbar, but not it's not. I am able to grab the vertical scrollbar and move it with my mouse, but not with scroll wheel.  

in Edge: cannot grab vertical scroll bar, but scroll wheel works when over the "data-simplebar" tagged element.

Cannot grab or move horizontal scroll bars in any way within either browser.

**Comment by jonagoldman** [comment]
I can confirm that this issue is related to the new 3.0 beta version. This does't happen in version 2.6.1.

**Comment by Grsmto** [comment]
FYI this issue has been fixed in a recent commit but I didn't do a release for it yet.
ref #179

**Comment by JDGHHou** [comment]
Ok, so I should wait for a new release, then? I tried grabbing commit #179 and it didn't work. I get Javascript errors saying SimpleBar doesn't exist when I try to use that file. 

It looks like it's using a completely different constructor for the SimpleBar object: TypeScript-style export defaults and such. This is in contrast to the 3.0.0 beta code that starts with "(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :"

Meanwhile, I have some grid controls in my scrolling DIVs that are wider than their containers. For now I have no way of seeing the off-screen content in them because the "drag" event doesn't fire on the horizontal bar. It works well on the vertical scroll bar. I may try to fall back to 2.6.1 and see if that fixes it.

**Comment by jonagoldman** [comment]
New release available, but now the vertical scrollbar ia not working for me 😶

**Comment by Grsmto** [comment]
Hey,
I think I fixed most of this.
However, on Edge it seems like I can't scroll horizontally with the mousewheel/trackpad even on native scrollbar. But I'm using Browserstack to test so maybe that's a limitation on their side.

**Comment by JDGHHou** [comment]
That's great news! Is it checked into a branch somewhere? I looked around in the repository and the last update I see was on August 9.

**Comment by Grsmto** [comment]
@JDGHHou should be solved in the latest release. Thanks again for your report.

**Comment by tbobinac** [comment]
It seemes that this still doesn't work, i tried with versions 3.0.0-beta.1 nad 3.1.0-beta.2

**Comment by AllanOricil** [comment]
2021 and it still does not work
