### ISSUE TITLE
Scrollbar doesn't autohide `onmouseleave`

### ISSUE THREAD

**Issue by yaymukund** [Grsmto/simplebar#211]
![autohide-on-mouseleave](https://user-images.githubusercontent.com/590450/46024450-bb277c80-c0de-11e8-8b78-c041232903f2.gif)

Autohide doesn't always trigger when the cursor leaves the element. I believe this is inconsistent with previous versions. I tried adding an `onmouseleave` event that simply resets `mouseX` and `mouseY`, but throttling means that sometimes it'll fire in the wrong order:

1. `mousemove()`
2. `mousemove()` is throttled
3. `mouseleave()`
4. `mouseleave()` fires immediately because it's not throttled yet
5. throttled `mousemove()` fires, incorrectly displaying the scrollbar

**Comment by yaymukund** [comment]
@Grsmto thank you!

**Comment by Grsmto** [comment]
Fixed in latest version.

**Comment by empresarrollo** [comment]
I just started using this plugin (it's great!) and it is still present this error.
What I installed:

```
λ npm install simplebar-vue --save
`-- simplebar-vue@0.1.0-beta.2
  `-- simplebar@3.0.0-beta.5
    +-- can-use-dom@0.1.0
    +-- lodash.throttle@4.1.1
    +-- resize-observer-polyfill@1.5.0
    `-- scrollbarwidth@0.1.3
```
