### ISSUE TITLE
[Landing page] Horizontal bars are sometimes needlessly showing ..

### ISSUE THREAD

**Issue by Rush** [Grsmto/simplebar#231]
The broken behavior can be observed on https://grsmto.github.io/simplebar/

I can also observe it with latest beta

## Current Behavior
![](https://rush.sh/2Z0i3zvB0j23P+l_9ktzkT1lM9Y/screenshot.png)

## Expected behavior

Horizontal bar to not show

## Reproducible example
Open https://grsmto.github.io/simplebar/

## Suggested solution(s)

No idea

## Additional context

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | Same as on https://grsmto.github.io/simplebar/
| Browser          |  Version 70.0.3538.77 (Official Build) (64-bit)
| npm/Yarn         | None
| Operating System | Linux / openSUSE Tumbleweed

**Comment by Grsmto** [comment]
Interesting. I'm not having this.
That might be a Linux + Chrome specific issue. Unfortunately I don't have Linux and it's not available on Browserstack so I can't test :/

**Comment by Demivan** [comment]
I encountered similar issue with IE 10. I fixed it with fix similar to #174. This one could be same issue.
I think cause is that size calculations are not exact in some browsers if container or content sizes are not integers in pixels.

**Comment by ChrisSympatient** [comment]
![unbenannt](https://user-images.githubusercontent.com/37874240/48699885-d00a2300-ebea-11e8-97b6-ad4b7812c66d.JPG)
![unbenannt2](https://user-images.githubusercontent.com/37874240/48699887-d00a2300-ebea-11e8-946a-be2351c80960.JPG)

I have the same issue. In debug mode, getting rid of the width: inherit seems to fix it, but since this is coming from sata-simplebar I cant change it, or am I getting something wrong here?

testable here ;)
www.hinz.design

**Comment by Grsmto** [comment]
@ChrisSympatient you are setting `overflow-y: scroll`, that breaks the plugin.
Also your own css is added before SimpleBar's css, that's why your `width` is overriden.

**Comment by ChrisSympatient** [comment]
@Grsmto Thank you very much for the quick reply!!! :)

I commented 	/* overflow-y: scroll;*/ out (style.css Line 1480)

and changed the css rel in the index file so simplebar is first:
  <link rel="stylesheet" href="https://unpkg.com/simplebar@latest/dist/simplebar.css" />

    <link rel="stylesheet" type="text/css"  href="css/style.css">
    <link rel="stylesheet" type="text/css" href="css/responsive.css">
...

But now the formating of the form is fully ***ed :D

![unbenannt](https://user-images.githubusercontent.com/37874240/48703801-3005c700-ebf5-11e8-91fc-0217d3ea981e.JPG)

My endless programming skills are quiet limited :D i guess Im missing out on major things here.

**Comment by Grsmto** [comment]
Yeah that's the `height: inherit` from SimpleBar breaking your layout (we might not need this property...). Apply `height: auto` to your div, that will fix it.
But you need to remove `overflow-y: scroll` or you will necessarily have the scrollbar track visible.

**Comment by ChrisSympatient** [comment]
Oh but I want the y bar to show. Because when a user enters a really long message and receives my "fake reply" the content will scroll down. Since the vertical scrollbar is there already, I dont have to bother rearranging the content. My concern was regarding the yellow marked horizontal scroll bar shown in the first screenshot i posted.

So actually everything is working just fine now, thanks to your advice rearranging the css rel order. Im just worried I actually miss your point and sound like a douche.

**Comment by Demivan** [comment]
@Grsmto It is reproduced not only on Linux: https://github.com/Grsmto/simplebar/issues/231#issuecomment-439344211
![default](https://user-images.githubusercontent.com/2339406/48772470-29e31980-eccd-11e8-8398-31524b2bfc44.png)
Reproduced on IE11 on https://grsmto.github.io/simplebar/  by setting container width to 171.78px

**Comment by Grsmto** [comment]
I don't get it, just tested on browserstack now and I can't reproduce this :/

![screenshot 2018-11-20 at 10 29 28](https://user-images.githubusercontent.com/527559/48773710-5425de80-ecaf-11e8-9783-a5e4a6545c70.jpg)

Any other things you're doing to get this? Like browser zoom level etc.?
What Windows version?

**Comment by Demivan** [comment]
Went to check my zoom level but now I cannot reproduce it too :/
IE: 11.345.17134.0
Windows 10: 1803

**Comment by Grsmto** [comment]
By the way it's worth noting that you can work-around this issue by explicitly setting `overflow-x: hidden` to your element, if you don't need horizontal scroll at all of course.

**Comment by akvaliya** [comment]
I am facing the same issue with google chrome 71.0.3578.98 (Official Build) (64-bit) in windows 10.
Did anyone found any solution?

**Comment by adjourn** [comment]
Im able to reproduce this but it seems to happens in very special conditions. For me it's when I zoom back and forth a lot and even then it only happens sometimes. Tried both Windows 10 and Ubuntu, Chrome and Chromium respectively. 

State of the world when it happens:

### Mount
![1](https://user-images.githubusercontent.com/17890701/51621489-4bff4f00-1f3d-11e9-842f-9581b5b1ac24.png)

### Wrapper
![2](https://user-images.githubusercontent.com/17890701/51621485-4ace2200-1f3d-11e9-8de1-c2a1307003b7.png)

### Observer
![3](https://user-images.githubusercontent.com/17890701/51621484-4ace2200-1f3d-11e9-9bae-2274a9f937aa.png)

### Mask 
![4](https://user-images.githubusercontent.com/17890701/51621482-4a358b80-1f3d-11e9-8d60-5bb689db1af7.png)

### Offset
![5](https://user-images.githubusercontent.com/17890701/51621481-499cf500-1f3d-11e9-805e-6bc85de25b03.png)

### Content
![6](https://user-images.githubusercontent.com/17890701/51621479-49045e80-1f3d-11e9-8f61-df14639a71ae.png)

### Actual content
![7](https://user-images.githubusercontent.com/17890701/51621477-49045e80-1f3d-11e9-9d55-d16b86534a23.png)

### Placeholder
![8](https://user-images.githubusercontent.com/17890701/51621476-49045e80-1f3d-11e9-8647-7cd0532e584f.png)

### Track
![9](https://user-images.githubusercontent.com/17890701/51621474-486bc800-1f3d-11e9-8b52-af569f0a15dd.png)

### Scrollbar
![10](https://user-images.githubusercontent.com/17890701/51621472-486bc800-1f3d-11e9-80db-ac37aaf15f34.png)

**Comment by Grsmto** [comment]
That's awesome @adjourn thanks for this!
I'll take a look when I can but it seems like it's some sub-pixel calculation issue and hopefully that should be easy to fix with a safeguard of ~1px in the calculation!

**Comment by akvaliya** [comment]
@Grsmto I tried in different system & found out that when windows 10 system resolution is 150% then horizontal scrollbar is always visible. Maybe this will help you identify the issue.

**Comment by Grsmto** [comment]
Hey guys,

FYI I just released `simplebar@4.0.0-alpha.0`, I would appreciate if you could test that out and let me know if that fixes the issue! 🤞
Thanks!

**Comment by briice** [comment]
Hi @Grsmto, I'm using `simplebar@4.0.0` and I still see this issue on Win10/Edge running in Fusion on a Mac. Not sure what's causing it though, and I haven't found an easy fix yet. For example if I set `width: 99%` and select/deselect it a couple times, sometimes it disappears, but it mostly doesn't.

<img width="591" alt="scrollbars" src="https://user-images.githubusercontent.com/102682/59073082-76adcc80-887a-11e9-9f5d-366c2ff59f02.png">

**Comment by Grsmto** [comment]
@briice if you could provide a reproductible case using the jsfiddle template that would help a lot to debug this issue further: https://jsfiddle.net/Grsmto/57obe5w2/1/
Thanks!

**Comment by kakigorimochi** [comment]
Is this fixed? I am also having problem with it on edge. 
There is nothing to scroll from yet the scrollbar is visible.

![image](https://user-images.githubusercontent.com/16938949/61365300-1159ec00-a8ba-11e9-92f6-d611004d99fc.png)

I am using ^3.1.0-beta.2

**Comment by kakigorimochi** [comment]
Updated to 4.1.0

Now it just sticks up top.
![image](https://user-images.githubusercontent.com/16938949/61366354-fee0b200-a8bb-11e9-9011-08583d34558a.png)

**Comment by AleCaste** [comment]
I am experiencing the same issue on both Edge and IE11, but for vertical scrollbar.
They are shown even when there is no need.
I noticed the size calculations are not accurate to the pixel when there are elements in the scrollable area with margins/paddings. 
Maybe something like this would help with subpixels differences:
```
this.axis.y.isOverflowing = Math.floor(this.contentWrapperEl.scrollHeight) > Math.ceil(this.contentWrapperEl.offsetHeight)
```
Likewise for horizontal axis.

**Comment by St-Permiakov** [comment]
I encountered same issue (needless scroll) on IE 11.
The "blue browser" is calculating width funny: on specific window widths (e.x. 1276) I get `scrollWitdh: 1090 offsetWidth: 1089` and on window width 1260 it's already accurate: `scrollWitdh: 1076 offsetWidth: 1076`.

What's even more surprising, there's no native scrollbar in both cases, but simplebar is placing it's scroll in the first one.

I don't know sandboxes still supporting IE, so can't provide you with working example just yet.

I guess IE just rounds offsetWidth and scrollWidth differently and there's not much to be done, but...
Has someone dealt with this before?

**Comment by AlexanderShchedrin** [comment]
I noticed a similar problem in FireFox. When calculating the value from scrollHeight, it is greater than offsetHeight. Because of this, scroll appears. This happens when scrolling horizontally. FireFox version is 125.0.3 64 bit

` this.axis.y.isOverflowing = contentElScrollHeight > contentWrapperElOffsetHeight;`

![image](https://github.com/Grsmto/simplebar/assets/107990239/92e9a84a-bf4f-4407-84dc-a0be66a52d7f)

![image](https://github.com/Grsmto/simplebar/assets/107990239/b1a7a009-96b2-4cf3-843f-629355b64b7f)
