### ISSUE TITLE
Glitch resizing a div caused by simplebar

### ISSUE THREAD

**Issue by villeneuve-michael** [Grsmto/simplebar#253]
## Current Behavior

I have an application and I want to resize a div width. The application layout has 3 column: 
- 2 fixed sidebar (left and right)
- 1 main container in the middle

There is 1 of my sidebar that I want to resize (view the screecast below).

Without the plugin enabled, all is perfect. However, when I activated simplebar, there was a weird behaviour where the sidebar would expand offscreen.

## Expected behavior

I want the div the resize as expected

## Reproducible example

Since it's a pretty big app, it's easier for me to share the problem via [screencast](https://drive.google.com/file/d/18s15-yjx2KdHOqrueAxoSd8jWeUG-O7U/view)

## Suggested solution(s)

So after playing with different options, I figured out the following solution : 

```css
.simplebar-placeholder {
  display: none;
}
```

## Additional context

Since I installed the plugin today, I didn't feel confortable issuing a pull request since maybe adding display: none will break other features.

**Comment by Grsmto** [comment]
Hi Michael,
It seems like the `simplebar-placeholder` is resizing properly from what I see in your screencast, so this might "just" be a CSS issue. Hard to say without seeing the code but how are you doing the "expand/minimize"? Is it a CSS animation? What's your CSS for this animation?

**Comment by Spegeli** [comment]
I installed this scrollbar plugin and i can confirm this issue.

placeholder enabled / showen:
http://i.epvpimg.com/YNMLdab.png

placeholder disabled / hidden:
http://i.epvpimg.com/GaIhcab.png

My page is normal ~950px high but the placeholder makes it ~1500px.

**Comment by villeneuve-michael** [comment]
@Grsmto 

It's a simple transition. I toggle the expand class on my sidebar:
```scss
aside {
  flex: 0 0 auto;
  width: 260px;
  &.expand {
     width: 520px;
  }

  -webkit-transition: width .25s;
  -moz-transition: width .25s;
  -ms-transition: width .25s;
  -o-transition: width .25s;
  transition: width .25s;
}

```

**Comment by adjourn** [comment]
I always encourage to make a minimum example that highlights the bug, fixes could take forever if author(s) have to reproduce every bug themselves based on screencast or description.  

@Grsmto [This example](https://jsfiddle.net/9n5woazk/) should highlight the problem. 

Im not sure what to make out of this bug because center placeholder gets resized/recalculated only if it has `display: none;` style. I tried to hack with `el.recalculate()` but I don't have anything good to show.

**Comment by adjourn** [comment]
@Grsmto Are you sure? It looks like video shows sidebar placeholder styles but the problem (as I see it) is that center placeholder doesn't resize. Sidebars have fixed `width` and center is supposed to take the remaining space, however if sidebar width is increased, center placeholder remains fixed `width` (it should decrease) and sidebar has no other choice but to grow off-screen.

`display: none;` works for him because he applies it to simplebar class and it gets applied to center placeholder as well. Only center placeholder needs it to get rid of the bug (as shown in my example).

But I don't know, maybe I misunderstood it. That's why demo would have been nice. Good luck!

**Comment by Grsmto** [comment]
@adjourn yeah you're right actually! Thanks for your help.

**Comment by Grsmto** [comment]
Until I figure out a solution for this, best workaround would be to force `width: auto` on `placeholder
`: `.simplebar-placeholder { width: auto!important; }`.

**Comment by Grsmto** [comment]
Should be fixed in `simplebar@4.0.0-alpha.0`!

**Comment by realthemes** [comment]
@Grsmto , Is this right place for comment? It is year 2023 and i encounter this error againe, I forced to use that fix `.simplebar-placeholder { width: auto!important; }` to fix my simplebar container width that can be changed by sidebar opening and closing

**Comment by bamtheboozle** [comment]
this is still happening within a flex div. adding width auto to the simplebar-placeholder fixes it. otherwise, the content scales when increasing width but never scales back down
