### ISSUE TITLE
simplebar.js:3780: Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by adamgreenough** [Grsmto/simplebar#360]
Hi! Any pointers on what could be causing this error would be much appreciated.

**Describe the bug**

The following console error when clicking the scrollbar: *"simplebar.js:3780 Unable to preventDefault inside passive event listener invocation"* (latest Chrome on macOS). Similar error in Firefox.

Actual functionality seems to be unaffected. 
**To Reproduce**

1. Visit https://hoard.fyi in Chrome
2. Click scrollbar on homepage carousels

**Comment by adamgreenough** [comment]
Oh, I've actually just noticed it happens on your demo site also: http://grsmto.github.io/simplebar/

**Comment by Grsmto** [comment]
Thanks for your report, it's actually already fixed in #358 and should be merged  soon.

**Comment by Grsmto** [comment]
Released.

**Comment by jairlopez** [comment]
It looks like it's still showing up after clicking on the scrollbar, on small screens. See picture below (It's Chromium 79.0.3945.88). This error appears twice per click.
![2020-01-17-13 57 51-1](https://user-images.githubusercontent.com/2719644/72636031-917a1080-3934-11ea-8c60-d60232174db7.png)
