### ISSUE TITLE
Gatsy app build failure - simplebar-react - 2.0.3-corejs2

### ISSUE THREAD

**Issue by KrishnaPrasanthVemuganti** [Grsmto/simplebar#396]
Getting below error when using  _"simplebar-react": "2.0.3-corejs2"_

> failed Building development bundle - 9.075s
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> Can't resolve 'core-js/modules/es.array.filter' in '/Users/krishna/Working/krishnaprasanth.com/node_modules/simplebar/dist'
> 
> File: node_modules/simplebar/dist/simplebar-core.esm.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> Can't resolve 'core-js/modules/es.array.for-each' in '/Users/krishna/Working/krishnaprasanth.com/node_modules/simplebar/dist'
> 
> File: node_modules/simplebar/dist/simplebar-core.esm.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> Can't resolve 'core-js/modules/es.array.iterator' in '/Users/krishna/Working/krishnaprasanth.com/node_modules/simplebar/dist'
> 
> File: node_modules/simplebar/dist/simplebar-core.esm.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> Can't resolve 'core-js/modules/es.object.assign' in '/Users/krishna/Working/krishnaprasanth.com/node_modules/simplebar/dist'
> 
> File: node_modules/simplebar/dist/simplebar-core.esm.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> Can't resolve 'core-js/modules/es.object.to-string' in '/Users/krishna/Working/krishnaprasanth.com/node_modules/simplebar/dist'
> 
> File: node_modules/simplebar/dist/simplebar-core.esm.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> Can't resolve 'core-js/modules/es.parse-int' in '/Users/krishna/Working/krishnaprasanth.com/node_modules/simplebar/dist'
> 
> File: node_modules/simplebar/dist/simplebar-core.esm.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> Can't resolve 'core-js/modules/es.string.iterator' in '/Users/krishna/Working/krishnaprasanth.com/node_modules/simplebar/dist'
> 
> File: node_modules/simplebar/dist/simplebar-core.esm.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> Can't resolve 'core-js/modules/es.weak-map' in '/Users/krishna/Working/krishnaprasanth.com/node_modules/simplebar/dist'
> 
> File: node_modules/simplebar/dist/simplebar-core.esm.js
> 
> 
>  ERROR #98123  WEBPACK
> 
> Generating development JavaScript bundle failed
> 
> Can't resolve 'core-js/modules/web.dom-collections.iterator' in '/Users/krishna/Working/krishnaprasanth.com/node_modules/simplebar/dist'
> 
> File: node_modules/simplebar/dist/simplebar-core.esm.js

package.json

```
"dependencies": {
    "@emotion/core": "^10.0.22",
    "gatsby": "^2.17.2",
    "gatsby-plugin-react-helmet": "^3.1.13",
    "gatsby-plugin-sass": "^2.1.20",
    "gatsby-plugin-typography": "^2.3.14",
    "node-sass": "^4.13.0",
    "react": "^16.11.0",
    "react-burger-menu": "^2.6.11",
    "react-dom": "^16.11.0",
    "react-helmet": "^5.2.1",
    "react-icons": "^3.7.0",
    "react-spinners": "^0.6.1",
    "react-typography": "^0.16.19",
    "simplebar-react": "2.0.3-corejs2",
    "typography": "^0.16.19",
    "typography-theme-github": "^0.16.19"
  },
  "devDependencies": {
    "prettier": "^1.18.2"
  }
```

This was fixed #387. Was working fine in _simplebar-react@2.0.2-corejs2-1_

**Comment by Grsmto** [comment]
I released a new version that hopefully fixed this. `simplebar-react@2.0.4-corejs2`

**Comment by garciaalvaro** [comment]
@Grsmto I still get these errors with the latest version. Is there any way around it? Thanks.
