### ISSUE TITLE
Double scrollbars showing up (both native and simplebar)

### ISSUE THREAD

**Issue by mikekok** [Grsmto/simplebar#73]
I added simplebar to my project (using the script tag) and then simply added `data-simplebar` at the element I need to display the custom scrollbar at.
The problem is, both the native scrollbar and simplebar showed up, and this happens to every element I try to add simplebar to.
Currently running Windows 10. Used simplebar on a node project built on Electron, which uses Chromium 56.

![problem](http://i.imgur.com/BghTMTJ.png)

**Comment by Grsmto** [comment]
Hey, @mikekok a new version will be released tomorrow, if you can tell me again if this is happening with the new version that would be great.
Thank you.

**Comment by mikekok** [comment]
Great! I will test it out tomorrow and let you know.

**Comment by Grsmto** [comment]
Hi, I just release a new version 2.3.0 that should solve this issue. Let me know, thanks!
https://github.com/Grsmto/simplebar/releases/tag/v2.3.0

**Comment by mikekok** [comment]
Unfortunately, the problem persists.
I still get two scrollbars.

**Comment by Grsmto** [comment]
Hey, I think I know where it comes from. Can you try adding `box-sizing: content-box;` to `.simplebar-scroll-content`?

**Comment by mikekok** [comment]
Perfect, the native scrollbar disappeared and everything is fine now!
Thanks a lot, I will choose simplebar over anything else.

**Comment by artaommahe** [comment]
@Grsmto same issue with `2.3.1`
![image](https://cloud.githubusercontent.com/assets/1944061/25093664/ee7b679a-239b-11e7-9fd7-8682c48e1b34.png)
 also click on rail does not scroll to that position, only bar dragging works

**Comment by KristinEliseLee** [comment]
I had this show up for the horizontal bar, the CSS for '.simplebar-content' has 'box-sizing: border-box!important;' instead of content-box. Changing it to content box fixed it

**Comment by ajay-aroki** [comment]
Changing box-sizing not worked for Edge, need to add **-ms-overflow-style: none;**  to **.simplebar-content-wrapper**

**Comment by RanjeetEppa18** [comment]
I had same issue, where I was applying `data-simplebar` to content which was `flex: 1` and no `height` specified. 
Solution: set `height: 0` and `min-height:0` to content.
